spring:
  application:
    name: SpringTest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_test
    username: postgres
    password: 123456

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: spring_test
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: spring_test
    default-schema: spring_test

resilience4j:
  retry:
    instances:
      externalService:
        max-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        enable-randomized-wait: true
        randomized-wait-factor: 0.5

logging:
  level:
    org.hibernate.SQL: DEBUG
    io.github.resilience4j: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html