/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.springtest.api;

import com.example.springtest.api.model.AuthorCreateRequest;
import com.example.springtest.api.model.AuthorResponse;
import com.example.springtest.api.model.ErrorResponse;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "Author", description = "the Author API")
public interface AuthorApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /api/authors : Create author
     *
     * @param authorCreateRequest  (required)
     * @return Author created (status code 201)
     *         or Validation error (status code 400)
     */
    @Operation(
        operationId = "createAuthor",
        summary = "Create author",
        tags = { "Author" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Author created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthorResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Validation error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/authors",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<AuthorResponse> createAuthor(
        @Parameter(name = "AuthorCreateRequest", description = "", required = true) @Valid @RequestBody AuthorCreateRequest authorCreateRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"books\" : [ { \"id\" : 6, \"title\" : \"title\" }, { \"id\" : 6, \"title\" : \"title\" } ], \"name\" : \"name\", \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /api/authors/{id} : Delete author
     *
     * @param id  (required)
     * @return Author deleted (status code 204)
     *         or Author not found (status code 404)
     */
    @Operation(
        operationId = "deleteAuthor",
        summary = "Delete author",
        tags = { "Author" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Author deleted"),
            @ApiResponse(responseCode = "404", description = "Author not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/api/authors/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Void> deleteAuthor(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /api/authors/{id} : Get author by id
     *
     * @param id  (required)
     * @return Author found (status code 200)
     *         or Author not found (status code 404)
     */
    @Operation(
        operationId = "getAuthorById",
        summary = "Get author by id",
        tags = { "Author" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Author found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Author not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/api/authors/{id}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<AuthorResponse> getAuthorById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"books\" : [ { \"id\" : 6, \"title\" : \"title\" }, { \"id\" : 6, \"title\" : \"title\" } ], \"name\" : \"name\", \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /api/authors/{id} : Update author
     *
     * @param id  (required)
     * @param authorCreateRequest  (required)
     * @return Author updated (status code 200)
     *         or Validation error (status code 400)
     *         or Author not found (status code 404)
     */
    @Operation(
        operationId = "updateAuthor",
        summary = "Update author",
        tags = { "Author" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Author updated", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = AuthorResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Validation error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            }),
            @ApiResponse(responseCode = "404", description = "Author not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorResponse.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/api/authors/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<AuthorResponse> updateAuthor(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "AuthorCreateRequest", description = "", required = true) @Valid @RequestBody AuthorCreateRequest authorCreateRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"books\" : [ { \"id\" : 6, \"title\" : \"title\" }, { \"id\" : 6, \"title\" : \"title\" } ], \"name\" : \"name\", \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
